// Generated by CoffeeScript 1.10.0
(function() {
  window.myChromePlugTools = {
    privateKeyID: 'PRIVATE_KEY_ID',
    sendMsg: function(key, data) {
      data[privateKeyID] = key;
      return chrome.extension.sendRequest(data);
    },
    onReceive: function(keys, callback) {
      return chrome.extension.onMessage.addListener(function(obj, sender) {
        if (keys.contains(obj[privateKeyID])) {
          return callback(obj, obj[privateKeyID], sender);
        }
      });
    }
  };

}).call(this);

//# sourceMappingURL=myChromePlugTools.js.map
