// Generated by CoffeeScript 1.10.0
(function() {
  window.myCommonUITools = {
    addButton: function(getPosition, handler, text) {
      var btnClass, button;
      btnClass = 'positionButtonMeZ';
      button = "<button class='" + btnClass + "'>" + text + "</button>";
      getPosition().prepend(button);
      return $("button." + btnClass).click(handler);
    },
    addDefaultButton: function(getPosition, handler, text) {
      var button, id;
      id = 'addDefaultButtonIdZ';
      button = "<button id='" + id + "'>" + text + "</button>";
      getPosition().prepend(button);
      return $("button\#" + id).click(handler);
    },
    addUrlDefault: function(url, text) {
      var ele;
      ele = "<a href='" + url + "' >" + text + "</a>";
      return $('body').prepend(ele);
    },
    setTextDefault: function(text) {
      var ele, id, textEle;
      id = "addTextDefaultDivIdZ";
      ele = "<div id = '" + id + "'>" + text + "</div>";
      textEle = $("div\#" + id);
      if (textEle.length === 0) {
        return $('body').prepend(ele);
      } else {
        textEle.html('');
        return textEle.html(text);
      }
    }
  };

}).call(this);

//# sourceMappingURL=myCommonUITools.js.map
