// Generated by CoffeeScript 1.10.0
(function() {
  window.myCommonToolsZ = {
    fireActionByCusCondition: function(condionF, action, once, interval, delay) {
      var id;
      if (once == null) {
        once = true;
      }
      if (interval == null) {
        interval = 500;
      }
      if (delay == null) {
        delay = 100;
      }
      return id = setInterval(function() {
        if (condionF()) {
          if (once) {
            clearInterval(id);
          }
          return setTimeout(function() {
            return action();
          }, delay);
        }
      }, interval);
    }
  };

}).call(this);

//# sourceMappingURL=myCommonToolsZ.js.map
