// Generated by CoffeeScript 1.10.0

/*
依赖3个第三方类库
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.PageActionControllerZ = (function(superClass) {
    extend(PageActionControllerZ, superClass);


    /*
    1 means Sequential execution
     */

    function PageActionControllerZ() {
      this.parallelCount = 1;
      PageActionControllerZ.__super__.constructor.call(this);
    }


    /*
    顺序执行pageAction
     */

    PageActionControllerZ.prototype.doAction = function() {
      return async.mapLimit(this.pageActions, this.parallelCount, function(ele, callback) {
        return myCommonToolsZ.fireActionByCusCondition(function() {
          return ele.getFireCondition();
        }, function() {
          var err, rT;
          err = null;
          rT = ele.fireAction();
          if (rT && rT[1]) {
            err = rT[0];
          }
          return callback(err, rT);
        }, null, ele.delayTime);
      }, function(err, result) {
        if (err) {
          onError(err);
          return;
        }
        return onFinished(result);
      });
    };

    return PageActionControllerZ;

  })(PageActionController);

}).call(this);

//# sourceMappingURL=PageActionControllerZ.js.map
