// Generated by CoffeeScript 1.10.0
(function() {
  var slice = [].slice;

  window.PageAction = (function() {
    function PageAction() {}

    PageAction.prototype.fireAction = function() {};

    PageAction.prototype.getFireCondition = function() {
      return true;
    };

    PageAction.prototype.delayTime = 500;

    return PageAction;

  })();

  window.PageActionController = (function() {
    function PageActionController() {
      this.pageActions = [];
    }

    PageActionController.prototype.doAction = function() {};

    PageActionController.prototype.onFinished = function(result) {};

    PageActionController.prototype.onError = function(err) {};

    PageActionController.prototype.add = function() {
      var ele, eles, i, len, results;
      eles = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      results = [];
      for (i = 0, len = eles.length; i < len; i++) {
        ele = eles[i];
        results.push(this.pageActions.push(ele));
      }
      return results;
    };

    return PageActionController;

  })();

}).call(this);

//# sourceMappingURL=PageAction.js.map
